export const workerProfile = {
  name: 'Rajesh Kumar',
  phoneNumber: '+91 98765 43210',
  email: 'rajesh.kumar@email.com',
  healthId: 'HR-2024-WK-48291',
  role: 'WORKER',
  dateOfBirth: '15/06/1985',
  gender: 'Male',
  bloodGroup: 'B+',
  address: '123 MG Road, Mumbai, Maharashtra',
  emergencyContact: '+91 98765 43211',
  profileCompletion: 72,
};

export const medicalRecords = [
  {
    id: 1,
    date: '15 Dec 2024',
    doctor: 'Dr. Priya Sharma',
    hospital: 'AIIMS, Delhi',
    recordType: 'General Checkup',
  },
  {
    id: 2,
    date: '20 Nov 2024',
    doctor: 'Dr. Amit Patel',
    hospital: 'City Hospital, Mumbai',
    recordType: 'Blood Test',
  },
  {
    id: 3,
    date: '05 Oct 2024',
    doctor: 'Dr. Sneha Reddy',
    hospital: 'Apollo Hospital, Hyderabad',
    recordType: 'Vaccination',
  },
  {
    id: 4,
    date: '12 Aug 2024',
    doctor: 'Dr. Rajesh Gupta',
    hospital: 'PHC, Jaipur',
    recordType: 'Dental',
  },
  {
    id: 5,
    date: '28 Jun 2024',
    doctor: 'Dr. Meera Nair',
    hospital: 'KIMS, Kochi',
    recordType: 'Eye Test',
  },
];

export const consents = [
  {
    id: 1,
    requester: 'Dr. Priya Sharma',
    hospital: 'AIIMS, Delhi',
    recordType: 'General Checkup',
    requestDate: '20 Dec 2024',
    status: 'ACTIVE',
    expiryDate: '20 Jun 2025',
  },
  {
    id: 2,
    requester: 'Dr. Amit Patel',
    hospital: 'City Hospital, Mumbai',
    recordType: 'Blood Test',
    requestDate: '18 Dec 2024',
    status: 'PENDING',
    expiryDate: null,
  },
  {
    id: 3,
    requester: 'Dr. Sneha Reddy',
    hospital: 'Apollo Hospital, Hyderabad',
    recordType: 'Vaccination',
    requestDate: '15 Nov 2024',
    status: 'PENDING',
    expiryDate: null,
  },
  {
    id: 4,
    requester: 'Dr. Rajesh Gupta',
    hospital: 'PHC, Jaipur',
    recordType: 'Dental',
    requestDate: '10 May 2024',
    status: 'REVOKED',
    expiryDate: null,
  },
  {
    id: 5,
    requester: 'Dr. Meera Nair',
    hospital: 'KIMS, Kochi',
    recordType: 'Eye Test',
    requestDate: '01 Mar 2024',
    status: 'EXPIRED',
    expiryDate: '01 Sep 2024',
  },
];
