const medicalCamps = [
  {
    id: 'MC001',
    name: 'Free General Health Check-Up Camp',
    date: '2026-08-25',
    time: '09:00 AM - 04:00 PM',
    location: 'Sector 12 Community Hall, Gurugram',
    city: 'Gurugram',
    specialties: ['General', 'Cardiology', 'Eye Care'],
    feeType: 'free',
    description: 'Comprehensive health screening including BP, sugar, BMI, and eye check-up for workers and their families.',
    organizer: 'HealthRaahi + Civil Hospital',
    slotsTotal: 200,
    slotsBooked: 142,
    distance: 2.3,
  },
  {
    id: 'MC002',
    name: 'Dental Health Awareness Camp',
    date: '2026-09-02',
    time: '10:00 AM - 02:00 PM',
    location: 'Primary Health Centre, Dharavi, Mumbai',
    city: 'Mumbai',
    specialties: ['Dental', 'General'],
    feeType: 'free',
    description: 'Free dental check-up, cleaning, and oral hygiene awareness session.',
    organizer: 'Smile Foundation',
    slotsTotal: 150,
    slotsBooked: 87,
    distance: 5.1,
  },
  {
    id: 'MC003',
    name: 'Diabetes & Hypertension Screening',
    date: '2026-09-10',
    time: '08:00 AM - 12:00 PM',
    location: 'Municipal School Ground, Koramangala, Bengaluru',
    city: 'Bengaluru',
    specialties: ['Cardiology', 'Endocrinology'],
    feeType: 'free',
    description: 'Screening for diabetes, hypertension, and lifestyle diseases. Free blood tests included.',
    organizer: 'HealthRaahi + NIMHANS',
    slotsTotal: 300,
    slotsBooked: 210,
    distance: 3.7,
  },
  {
    id: 'MC004',
    name: 'Mother & Child Health Camp',
    date: '2026-09-15',
    time: '09:00 AM - 05:00 PM',
    location: 'Urban Health Centre, T Nagar, Chennai',
    city: 'Chennai',
    specialties: ['Gynecology', 'Pediatrics', 'General'],
    feeType: 'free',
    description: 'Prenatal and postnatal check-ups, immunization, nutrition counselling for mothers and children.',
    organizer: 'HealthRaahi + ICDS',
    slotsTotal: 250,
    slotsBooked: 180,
    distance: 1.8,
  },
  {
    id: 'MC005',
    name: 'Orthopaedic & Physiotherapy Camp',
    date: '2026-09-20',
    time: '10:00 AM - 03:00 PM',
    location: 'Workers Colony Community Centre, Andheri, Mumbai',
    city: 'Mumbai',
    specialties: ['Orthopaedics', 'Physiotherapy'],
    feeType: 'paid',
    description: 'Bone density test, posture assessment, and physiotherapy consultation at subsidized rates.',
    organizer: 'HealthRaahi + Kokilaben Hospital',
    slotsTotal: 100,
    slotsBooked: 45,
    distance: 7.2,
  },
  {
    id: 'MC006',
    name: 'Eye Care & Vision Screening Camp',
    date: '2026-09-25',
    time: '09:00 AM - 01:00 PM',
    location: 'Gram Panchayat Bhawan, Whitefield, Bengaluru',
    city: 'Bengaluru',
    specialties: ['Eye Care'],
    feeType: 'free',
    description: 'Free vision testing, glaucoma screening, and spectacle distribution for eligible workers.',
    organizer: 'HealthRaahi + Aravind Eye Hospital',
    slotsTotal: 180,
    slotsBooked: 160,
    distance: 4.5,
  },
  {
    id: 'MC007',
    name: 'Vaccination & Immunisation Drive',
    date: '2026-10-01',
    time: '08:00 AM - 06:00 PM',
    location: 'District Hospital Premises, Sector 30, Noida',
    city: 'Noida',
    specialties: ['General', 'Pediatrics'],
    feeType: 'free',
    description: 'COVID boosters, influenza vaccines, and routine immunisation for children under 5.',
    organizer: 'HealthRaahi + District Health Dept',
    slotsTotal: 500,
    slotsBooked: 320,
    distance: 6.0,
  },
  {
    id: 'MC008',
    name: 'Mental Health & Stress Management Camp',
    date: '2026-10-05',
    time: '11:00 AM - 04:00 PM',
    location: 'NGO Office Complex, Kothrud, Pune',
    city: 'Pune',
    specialties: ['Mental Health', 'General'],
    feeType: 'free',
    description: 'Confidential counselling, stress assessment, and mental wellness workshops for migrant workers.',
    organizer: 'HealthRaahi + Vandrevala Foundation',
    slotsTotal: 80,
    slotsBooked: 32,
    distance: 8.0,
  },
];

export default medicalCamps;
